services:
  postgres:
    image: bitnami/postgresql:17
    container_name: bun-auth-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=auth
