@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_acctount
POST {{baseUrl}}/accounts
content-type: application/json

{
    "name": "Demo",
    "email": "demo@demo.com",
    "password": "123123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
content-type: application/json

{
    "email": "demo@demo.com",
    "password": "123123"
}

###

# @name create_question
POST {{baseUrl}}/questions
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Qual é a sua cor favorita?",
    "content": "Qual é a sua cor favorita?"
}